#!/c/Program\ Files/Git/usr/bin/sh.exe

changedFiles="$(git diff-tree -r --name-only --no-commit-id ORIG_HEAD HEAD)"

runOnChange() {
	echo "$changedFiles" | grep -q "$1" && eval "$2"
}

runOnChange package-lock.json "npm install"
runOnChange pom.xml "rm -fr target/dependency/*; mvn install dependency:copy-dependencies;"

echo "git post-merge hook executed `date '+%d/%m/%Y %H:%M:%S'`" >> ~/gitHook.txt
