version: '3'
services:
  web:
    container_name: "web"
    build: ./web
    ports:
      - "80:8080"
  
  db:
    container_name: "db"
    build: ./db
    ports:
      - "5432:5432"
    restart: "always"
    environment:
      - POSTGRES_PASSWORD="Orion123"
