version: '3'
services:
  web:
    container_name: "web"
    env_file: .env
    build: ./web
    ports:
      - "80:8080"
  
  db:
    container_name: "db"
    env_file: .env
    build: ./db
    ports:
      - "15432:5432"
    restart: "always"
